Ensure threads are cancelled after execution
Because lambda doesn't actually stop the Python processes proper after
each execution the threads would linger around after finishing. After
enough invocations of your function it would start failing from:

    error: can't start new thread
      File "raven_python_lambda/__init__.py", line 176, in decorated
        install_timers(self.config, context)
      File "raven_python_lambda/__init__.py", line 231, in install_timers
        Timer(max(time_remaining - 500, 0), timeout_error, (config)).start()
      File "python2.7/threading.py", line 739, in start
        _start_new_thread(self.__bootstrap, ())

By collecting all the timers and then cancelling them at the end of
function execution we're no longer seeing this resource constraint.